"""SVG Renderer.

Renders PresentationModel into valid SVG visual cards using ThemePalette colors.
No animation logic. Animation belongs to Phase 9.
Governed by 09_RENDERING_SPECIFICATION.md.
"""

from profileforge.generators.models import PresentationModel
from profileforge.renderers.exceptions import SVGRenderError
from profileforge.renderers.models import SVGArtifact
from profileforge.renderers.renderer import BaseRenderer
from profileforge.renderers.theme_loader import ThemeLoader, ThemePalette


class SVGRenderer(BaseRenderer):
    """Concrete renderer for SVG visual card artifacts."""

    def __init__(self, theme_loader: ThemeLoader | None = None) -> None:
        self._theme_loader = theme_loader or ThemeLoader()

    def render(self, presentation_model: PresentationModel) -> list[SVGArtifact]:
        """Render presentation model into a list of SVG visual cards."""
        try:
            theme = self._theme_loader.get_active_theme()
            artifacts: list[SVGArtifact] = []

            # 1. Render Stats Card SVG
            stats_svg = self._render_stats_card(presentation_model, theme)
            artifacts.append(
                SVGArtifact(
                    identifier="stats_card",
                    card_name="Portfolio Statistics Card",
                    output_filename="stats_card.svg",
                    svg_content=stats_svg,
                    width=450,
                    height=200,
                )
            )

            # 2. Render Tech Stack Card SVG
            tech_svg = self._render_tech_card(presentation_model, theme)
            artifacts.append(
                SVGArtifact(
                    identifier="tech_card",
                    card_name="Technology Stack Card",
                    output_filename="tech_card.svg",
                    svg_content=tech_svg,
                    width=450,
                    height=200,
                )
            )

            return artifacts
        except Exception as exc:
            raise SVGRenderError(
                f"Failed to render SVG artifacts for user '{presentation_model.username}': {exc}"
            ) from exc

    def _render_stats_card(
        self, model: PresentationModel, theme: ThemePalette
    ) -> str:
        """Construct valid SVG markup for portfolio statistics card."""
        s = model.statistics
        name_display = model.profile.display_name or model.username
        return f"""<svg xmlns="http://www.w3.org/2000/svg" width="450" height="200" viewBox="0 0 450 200">
  <rect width="450" height="200" rx="10" fill="{theme.card_bg}" stroke="{theme.border_color}" stroke-width="1"/>
  <text x="25" y="40" font-family="{theme.font_family}" font-size="18" font-weight="bold" fill="{theme.accent_color}">{name_display}'s Portfolio Stats</text>
  <text x="25" y="80" font-family="{theme.font_family}" font-size="14" fill="{theme.text_primary}">Total Stars: {s.total_stars}</text>
  <text x="25" y="110" font-family="{theme.font_family}" font-size="14" fill="{theme.text_primary}">Total Forks: {s.total_forks}</text>
  <text x="25" y="140" font-family="{theme.font_family}" font-size="14" fill="{theme.text_primary}">Public Repos: {s.total_repositories}</text>
  <text x="25" y="170" font-family="{theme.font_family}" font-size="14" fill="{theme.text_secondary}">Primary Language: {s.dominant_language}</text>
</svg>"""

    def _render_tech_card(
        self, model: PresentationModel, theme: ThemePalette
    ) -> str:
        """Construct valid SVG markup for technology stack card."""
        tech_list = ", ".join(model.technology_stack.all_technologies[:6])
        return f"""<svg xmlns="http://www.w3.org/2000/svg" width="450" height="200" viewBox="0 0 450 200">
  <rect width="450" height="200" rx="10" fill="{theme.card_bg}" stroke="{theme.border_color}" stroke-width="1"/>
  <text x="25" y="40" font-family="{theme.font_family}" font-size="18" font-weight="bold" fill="{theme.accent_color}">Technology Stack</text>
  <text x="25" y="90" font-family="{theme.font_family}" font-size="14" fill="{theme.text_primary}">{tech_list}</text>
  <text x="25" y="150" font-family="{theme.font_family}" font-size="12" fill="{theme.text_secondary}">Generated by ProfileForge</text>
</svg>"""
