"""
Shared SVG styling constants.
"""

# Canvas
CANVAS_WIDTH = 1200
CANVAS_HEIGHT = 630

# Typography
TITLE_FONT_SIZE = 32
SUBTITLE_FONT_SIZE = 18
BODY_FONT_SIZE = 16
SMALL_FONT_SIZE = 13

FONT_WEIGHT_NORMAL = "normal"
FONT_WEIGHT_BOLD = "bold"

# Colors
COLOR_BACKGROUND = "#0d1117"
COLOR_SURFACE = "#161b22"
COLOR_BORDER = "#30363d"

COLOR_TEXT_PRIMARY = "#f0f6fc"
COLOR_TEXT_SECONDARY = "#8b949e"

COLOR_ACCENT = "#58a6ff"

# Shapes
DEFAULT_RADIUS = 12
DEFAULT_STROKE_WIDTH = 1